// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnzQgA6RBp9egQ9jvepc_hpGA2Hk5Aseo',
    appId: '1:1073374832398:web:1162082c4161a17089995f',
    messagingSenderId: '1073374832398',
    projectId: 'salary-290ff',
    authDomain: 'salary-290ff.firebaseapp.com',
    storageBucket: 'salary-290ff.firebasestorage.app',
    measurementId: 'G-GFD5RG7377',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9zLmsBbzAX41V0DL8TRhVcm3OI8t7OQw',
    appId: '1:1073374832398:android:cfe5dfeab178841089995f',
    messagingSenderId: '1073374832398',
    projectId: 'salary-290ff',
    storageBucket: 'salary-290ff.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnUaO0jTmON5upOAJsop_-4rUbVfu867s',
    appId: '1:915874825664:ios:e64e749c66349432447425',
    messagingSenderId: '915874825664',
    projectId: 'salary-31ac6',
    databaseURL: 'https://salary-31ac6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'salary-31ac6.firebasestorage.app',
    iosBundleId: 'com.example.salaryApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnUaO0jTmON5upOAJsop_-4rUbVfu867s',
    appId: '1:915874825664:ios:e64e749c66349432447425',
    messagingSenderId: '915874825664',
    projectId: 'salary-31ac6',
    databaseURL: 'https://salary-31ac6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'salary-31ac6.firebasestorage.app',
    iosBundleId: 'com.example.salaryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7h4FOcQWYxG67jlZA7_dsk_rX4Pfbyw0',
    appId: '1:915874825664:web:433a92c23238182a447425',
    messagingSenderId: '915874825664',
    projectId: 'salary-31ac6',
    authDomain: 'salary-31ac6.firebaseapp.com',
    databaseURL: 'https://salary-31ac6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'salary-31ac6.firebasestorage.app',
    measurementId: 'G-NF6L8S4LMJ',
  );
}
