import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import '../models/staff.dart';
import '../models/campus.dart';
import '../services/firebase_service.dart';

class AddEditStaffScreen extends StatefulWidget {
  final Staff? staff; // null for add, non-null for edit

  const AddEditStaffScreen({super.key, this.staff});

  @override
  State<AddEditStaffScreen> createState() => _AddEditStaffScreenState();
}

class _AddEditStaffScreenState extends State<AddEditStaffScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _salaryController = TextEditingController();
  final _phoneController = TextEditingController();
  final _passwordController = TextEditingController();
  
  // New Expanded Controllers
  final _fatherNameController = TextEditingController();
  final _cnicController = TextEditingController();
  final _addressController = TextEditingController();
  final _designationController = TextEditingController();
  final _joiningDateController = TextEditingController();
  final _bankAccountController = TextEditingController();
  final _emergencyContactController = TextEditingController();
  final _notesController = TextEditingController();
  String _salaryType = 'Monthly';

  String? _selectedCampus;
  List<Campus> _campuses = [];
  bool _isLoadingCampuses = true;
  final FirebaseService _firebaseService = FirebaseService();
  bool _isLoading = false;
  bool _isActive = true;
  bool get _isEditing => widget.staff != null;

  @override
  void initState() {
    super.initState();
    if (_isEditing) {
      _nameController.text = widget.staff!.name;
      _salaryController.text = widget.staff!.salary.toString();
      _phoneController.text = widget.staff!.phone;
      _selectedCampus = widget.staff!.campus;
      _isActive = widget.staff!.isActive;
      _passwordController.text = widget.staff!.password ?? '';
      
      _fatherNameController.text = widget.staff!.fatherHusbandName ?? '';
      _cnicController.text = widget.staff!.cnic ?? '';
      _addressController.text = widget.staff!.address ?? '';
      _designationController.text = widget.staff!.designation ?? '';
      _joiningDateController.text = widget.staff!.joiningDate ?? '';
      _bankAccountController.text = widget.staff!.bankAccount ?? '';
      _emergencyContactController.text = widget.staff!.emergencyContact ?? '';
      _notesController.text = widget.staff!.notes ?? '';
      _salaryType = widget.staff!.salaryType;
    }
    _loadCampuses();
  }

  @override
  void dispose() {
    _nameController.dispose();
    _salaryController.dispose();
    _phoneController.dispose();
    _passwordController.dispose();
    _fatherNameController.dispose();
    _cnicController.dispose();
    _addressController.dispose();
    _designationController.dispose();
    _joiningDateController.dispose();
    _bankAccountController.dispose();
    _emergencyContactController.dispose();
    _notesController.dispose();
    super.dispose();
  }

  Future<void> _loadCampuses() async {
    try {
      final campuses = await _firebaseService.getCampuses();
      if (mounted) {
        setState(() {
          _campuses = campuses;
          _isLoadingCampuses = false;
        });
      }
    } catch (e) {
      if (mounted) {
        setState(() => _isLoadingCampuses = false);
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(SnackBar(content: Text('Error loading campuses: $e')));
      }
    }
  }

  Future<void> _handleSubmit() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isLoading = true);

    try {
      final staff = Staff(
        id:
            widget.staff?.id ??
            '', // ID will be generated by Firestore for new staff
        name: _nameController.text.trim(),
        salary: double.parse(_salaryController.text.trim()),
        phone: _phoneController.text.trim(),
        campus: _selectedCampus!,
        isActive: _isActive,
        password: _passwordController.text.trim().isNotEmpty
            ? _passwordController.text.trim()
            : null,
        fatherHusbandName: _fatherNameController.text.trim(),
        cnic: _cnicController.text.trim(),
        address: _addressController.text.trim(),
        designation: _designationController.text.trim(),
        joiningDate: _joiningDateController.text.trim(),
        salaryType: _salaryType,
        bankAccount: _bankAccountController.text.trim(),
        emergencyContact: _emergencyContactController.text.trim(),
        notes: _notesController.text.trim(),
      );

      if (_isEditing) {
        await _firebaseService.updateStaff(widget.staff!.id, staff);
      } else {
        await _firebaseService.addStaff(staff);
      }

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(
              _isEditing
                  ? 'Staff updated successfully'
                  : 'Staff added successfully',
            ),
            backgroundColor: Colors.green,
          ),
        );
        Navigator.pop(context, true); // Return true to indicate success
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error: ${e.toString()}'),
            backgroundColor: Colors.red,
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(_isEditing ? 'Edit Staff' : 'Add Staff')),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              // Decorative header
              Center(
                child: Container(
                  width: 100,
                  height: 100,
                  decoration: BoxDecoration(
                    gradient: LinearGradient(
                      colors: [
                        Theme.of(context).colorScheme.primary,
                        Theme.of(context).colorScheme.secondary,
                      ],
                      begin: Alignment.topLeft,
                      end: Alignment.bottomRight,
                    ),
                    shape: BoxShape.circle,
                    boxShadow: [
                      BoxShadow(
                        color: Theme.of(
                          context,
                        ).colorScheme.primary.withValues(alpha: 0.3),
                        blurRadius: 20,
                        offset: const Offset(0, 10),
                      ),
                    ],
                  ),
                  child: const Icon(
                    Icons.person_add_rounded,
                    size: 50,
                    color: Colors.white,
                  ),
                ),
              ),
              const SizedBox(height: 12),
              Center(
                child: Text(
                  _isEditing ? 'Update Profile' : 'New Staff Member',
                  style: const TextStyle(
                    fontSize: 22,
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ),
              Center(
                child: Text(
                  'Fill in the details below',
                  style: TextStyle(
                    color: Theme.of(
                      context,
                    ).colorScheme.onSurface.withValues(alpha: 0.5),
                    fontSize: 14,
                  ),
                ),
              ),
              const SizedBox(height: 40),

              // Form fields section
              Container(
                padding: const EdgeInsets.all(24),
                decoration: BoxDecoration(
                  color: Theme.of(context).cardColor,
                  borderRadius: BorderRadius.circular(24),
                  border: Border.all(
                    color: Theme.of(context).dividerColor.withValues(alpha: 0.5),
                  ),
                  boxShadow: [
                    BoxShadow(
                      color: Colors.black.withValues(alpha: 0.02),
                      blurRadius: 20,
                      offset: const Offset(0, 10),
                    ),
                  ],
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const Text(
                      'PERSONAL INFORMATION',
                      style: TextStyle(
                        fontSize: 12,
                        fontWeight: FontWeight.bold,
                        letterSpacing: 1.2,
                        color: Colors.grey,
                      ),
                    ),
                    const SizedBox(height: 20),
                    TextFormField(
                      controller: _nameController,
                      decoration: InputDecoration(
                        labelText: 'Full Name',
                        prefixIcon: const Icon(Icons.person_outline_rounded),
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(16),
                        ),
                        filled: true,
                      ),
                      textCapitalization: TextCapitalization.words,
                      validator: (value) =>
                          (value == null || value.trim().isEmpty)
                          ? 'Name is required'
                          : null,
                    ),
                    const SizedBox(height: 20),
                    TextFormField(
                      controller: _fatherNameController,
                      decoration: InputDecoration(
                        labelText: 'Father / Husband Name',
                        prefixIcon: const Icon(Icons.family_restroom_rounded),
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(16),
                        ),
                        filled: true,
                      ),
                      textCapitalization: TextCapitalization.words,
                    ),
                    const SizedBox(height: 20),
                    TextFormField(
                      controller: _cnicController,
                      decoration: InputDecoration(
                        labelText: 'CNIC',
                        prefixIcon: const Icon(Icons.badge_outlined),
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(16),
                        ),
                        filled: true,
                      ),
                    ),
                    const SizedBox(height: 20),
                    TextFormField(
                      controller: _phoneController,
                      decoration: InputDecoration(
                        labelText: 'Phone Number',
                        prefixIcon: const Icon(Icons.phone_iphone_rounded),
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(16),
                        ),
                        filled: true,
                      ),
                      keyboardType: TextInputType.phone,
                      validator: (value) =>
                          (value == null || value.trim().isEmpty)
                          ? 'Phone number is required'
                          : null,
                    ),
                    const SizedBox(height: 20),
                    TextFormField(
                      controller: _addressController,
                      decoration: InputDecoration(
                        labelText: 'Home Address',
                        prefixIcon: const Icon(Icons.home_outlined),
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(16),
                        ),
                        filled: true,
                      ),
                      maxLines: 2,
                    ),
                    const SizedBox(height: 20),
                    TextFormField(
                      controller: _passwordController,
                      decoration: InputDecoration(
                        labelText: 'Password (Optional)',
                        hintText: 'Set login password',
                        prefixIcon: const Icon(Icons.lock_outline_rounded),
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(16),
                        ),
                        filled: true,
                        helperText: 'Allows staff to login to their account',
                      ),
                    ),
                    const SizedBox(height: 32),
                    const Text(
                      'EMPLOYMENT DETAILS',
                      style: TextStyle(
                        fontSize: 12,
                        fontWeight: FontWeight.bold,
                        letterSpacing: 1.2,
                        color: Colors.grey,
                      ),
                    ),
                    const SizedBox(height: 20),
                    TextFormField(
                      controller: _designationController,
                      decoration: InputDecoration(
                        labelText: 'Designation / Title',
                        prefixIcon: const Icon(Icons.work_outline_rounded),
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(16),
                        ),
                        filled: true,
                      ),
                    ),
                    const SizedBox(height: 20),
                    TextFormField(
                      controller: _joiningDateController,
                      decoration: InputDecoration(
                        labelText: 'Joining Date (e.g. 2026-06-21)',
                        prefixIcon: const Icon(Icons.calendar_today_rounded),
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(16),
                        ),
                        filled: true,
                      ),
                    ),
                    const SizedBox(height: 20),
                    DropdownButtonFormField<String>(
                      initialValue: _salaryType,
                      decoration: InputDecoration(
                        labelText: 'Salary Type',
                        prefixIcon: const Icon(Icons.category_rounded),
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(16),
                        ),
                        filled: true,
                      ),
                      items: const [
                        DropdownMenuItem(value: 'Monthly', child: Text('Monthly')),
                        DropdownMenuItem(value: 'Lecture', child: Text('Lecture Based')),
                      ],
                      onChanged: (v) => setState(() => _salaryType = v!),
                    ),
                    const SizedBox(height: 20),
                    TextFormField(
                      controller: _salaryController,
                      decoration: InputDecoration(
                        labelText: 'Basic Salary / Rate',
                        prefixIcon: const Icon(
                          Icons.account_balance_wallet_outlined,
                        ),
                        prefixText: 'Rs ',
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(16),
                        ),
                        filled: true,
                      ),
                      keyboardType: TextInputType.number,
                      inputFormatters: [FilteringTextInputFormatter.digitsOnly],
                      validator: (value) {
                        if (value == null || value.trim().isEmpty) {
                          return 'Salary is required';
                        }
                        final s = double.tryParse(value);
                        if (s == null || s <= 0) return 'Enter a valid salary';
                        return null;
                      },
                    ),
                    const SizedBox(height: 20),
                    _isLoadingCampuses
                        ? const Center(child: LinearProgressIndicator())
                        : DropdownButtonFormField<String>(
                            initialValue:
                                _campuses.any((c) => c.name == _selectedCampus)
                                ? _selectedCampus
                                : null,
                            decoration: InputDecoration(
                              labelText: 'Assign Campus',
                              prefixIcon: const Icon(Icons.business_rounded),
                              border: OutlineInputBorder(
                                borderRadius: BorderRadius.circular(16),
                              ),
                              filled: true,
                            ),
                            items: _campuses
                                .map(
                                  (c) => DropdownMenuItem(
                                    value: c.name,
                                    child: Text(c.name),
                                  ),
                                )
                                .toList(),
                            onChanged: (v) =>
                                setState(() => _selectedCampus = v),
                            validator: (v) => (v == null || v.isEmpty)
                                ? 'Please select a campus'
                                : null,
                          ),
                  ],
                ),
              ),
              const SizedBox(height: 24),
              
              // Additional Details Section
              Container(
                padding: const EdgeInsets.all(24),
                decoration: BoxDecoration(
                  color: Theme.of(context).cardColor,
                  borderRadius: BorderRadius.circular(24),
                  border: Border.all(
                    color: Theme.of(context).dividerColor.withValues(alpha: 0.5),
                  ),
                  boxShadow: [
                    BoxShadow(
                      color: Colors.black.withValues(alpha: 0.02),
                      blurRadius: 20,
                      offset: const Offset(0, 10),
                    ),
                  ],
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const Text(
                      'ADDITIONAL DETAILS',
                      style: TextStyle(
                        fontSize: 12,
                        fontWeight: FontWeight.bold,
                        letterSpacing: 1.2,
                        color: Colors.grey,
                      ),
                    ),
                    const SizedBox(height: 20),
                    TextFormField(
                      controller: _bankAccountController,
                      decoration: InputDecoration(
                        labelText: 'Bank Account Number / IBAN',
                        prefixIcon: const Icon(Icons.account_balance_rounded),
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(16),
                        ),
                        filled: true,
                      ),
                    ),
                    const SizedBox(height: 20),
                    TextFormField(
                      controller: _emergencyContactController,
                      decoration: InputDecoration(
                        labelText: 'Emergency Contact Info',
                        prefixIcon: const Icon(Icons.health_and_safety_rounded),
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(16),
                        ),
                        filled: true,
                      ),
                    ),
                    const SizedBox(height: 20),
                    TextFormField(
                      controller: _notesController,
                      decoration: InputDecoration(
                        labelText: 'Internal Notes',
                        prefixIcon: const Icon(Icons.note_alt_outlined),
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(16),
                        ),
                        filled: true,
                      ),
                      maxLines: 3,
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 24),

              // Status Switch Card
              Container(
                decoration: BoxDecoration(
                  color: Theme.of(context).cardColor,
                  borderRadius: BorderRadius.circular(20),
                  border: Border.all(
                    color: Theme.of(context).dividerColor.withValues(alpha: 0.5),
                  ),
                ),
                child: SwitchListTile(
                  title: const Text(
                    'Active Status',
                    style: TextStyle(fontWeight: FontWeight.w600),
                  ),
                  subtitle: const Text('Allow salary and attendance records'),
                  value: _isActive,
                  onChanged: (v) => setState(() => _isActive = v),
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(20),
                  ),
                  activeThumbColor: Theme.of(context).colorScheme.primary,
                ),
              ),
              const SizedBox(height: 32),

              // Action Buttons
              Row(
                children: [
                  Expanded(
                    child: SizedBox(
                      height: 56,
                      child: OutlinedButton(
                        onPressed: _isLoading
                            ? null
                            : () => Navigator.pop(context),
                        style: OutlinedButton.styleFrom(
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(16),
                          ),
                        ),
                        child: const Text('Cancel'),
                      ),
                    ),
                  ),
                  const SizedBox(width: 16),
                  Expanded(
                    flex: 2,
                    child: SizedBox(
                      height: 56,
                      child: ElevatedButton(
                        onPressed: _isLoading ? null : _handleSubmit,
                        style: ElevatedButton.styleFrom(
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(16),
                          ),
                          elevation: 8,
                          shadowColor: Theme.of(
                            context,
                          ).colorScheme.primary.withValues(alpha: 0.4),
                        ),
                        child: _isLoading
                            ? const SizedBox(
                                height: 24,
                                width: 24,
                                child: CircularProgressIndicator(
                                  strokeWidth: 2,
                                  color: Colors.white,
                                ),
                              )
                            : Text(
                                _isEditing ? 'Save Changes' : 'Add Member',
                                style: const TextStyle(
                                  fontWeight: FontWeight.bold,
                                ),
                              ),
                      ),
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 24),
            ],
          ),
        ),
      ),
    );
  }
}
